apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste
  name: teste
  namespace: teste
spec:
  containers:
  - command:
    - 'sleep 3600'
    image: busybox
    name: teste
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
