---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1h
  ref:
    branch: main
  secretRef:
    name: github-instavote
  url: https://github.com/alexcastilio/instavote-deploy

