---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: projects
  namespace: flux-system
spec:
  interval: 1h
  path: ./projects/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

