---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-deploy
  namespace: monitoring
spec:
  interval: 1h
  path: ./flux
  prune: false
  serviceAccountName: monitoring
  sourceRef:
    kind: GitRepository
    name: monitoring-deploy
