---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: monitoring-deploy
  namespace: monitoring
spec:
  interval: 1h
  ref:
    branch: main
  url: https://github.com/alexcastilio/monitoring-deploy
